.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH cornelli 1  "cornelli 1.3.0" 
.SH NAME
cornelli \- Write to your future self.
.SH SYNOPSIS
\fBcornelli\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Write to your future self.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
cornelli\-keep(1)
Keep a new capsule of thoughts
.TP
cornelli\-mailbox(1)
Visit your mailbox
.TP
cornelli\-burn(1)
Burns the mailbox forever
.TP
cornelli\-path(1)
Shows the path to the mailbox core
.TP
cornelli\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v1.3.0
